### ISSUE TITLE
Error reading from database - running custom reports on Reporting Dashboard

### ISSUE THREAD

**Issue by stevenlovidge** [cwarwicker/moodle-block_elbp#13]
Results
Error reading from database

More information about this error

Continue

**Comment by cwarwicker** [comment]
Hi,

I've uploaded new versions of all 3 blocks:

block_bc_dashboard
block_elbp
block_gradetracker

Which should fix the reporting issue hopefully, as well as a few other 
small bugs.

Let me know how you get on with it.


Also, I've attached the XML files of the custom PLP blocks we created at 
Bedford last year if you wanted to see if they are of any use. Just go 
to PLP -> Configuration -> Plugins and "Import Custom Plugin" and choose 
the XML file. You can then Enable the plugin, add it to a layout, etc... 
as you would with normal plugins.



Conn
