### ISSUE TITLE
Running a report

### ISSUE THREAD

**Issue by Smithy31** [cwarwicker/moodle-block_elbp#27]
Hi 

Every time I go to run a report I receive the following error, not quite sure why this is happening.

Exception - Call to undefined function gt_get_course()

Regards

Smithy31

**Comment by cwarwicker** [comment]
Hi,

Which reports is it you're trying to run? Could you give me a list of steps which leads to this error?

Thanks.

**Comment by Smithy31** [comment]
Hi
I'm am trying to run a report to show the number of students enrolled on a specific course, I used the following steps: Create, I enter details and  a description, Course type Parent /Standard Courses, Starting Point 2017 /2018 courses, Visibility Student Induction, I add a filter: Enrol, Comparison equals==, Value >0, then I save and run the report.  Hope this makes sense.

Regards

Smithy31

**Comment by Smithy31** [comment]
Hi
I'm am trying to run a report to show the number of students enrolled on a specific course, I used the following steps: Create, I enter details and a description, Course type Parent /Standard Courses, Starting Point 2017 /2018 courses, Visibility Student Induction, I add a filter: Enrol, Comparison equals==, Value >0, then I save and run the report. Hope this makes sense.

Regards

Smithy31

**Comment by cwarwicker** [comment]
Hi, i'm closing this issue and will update the one in the bc_dashboard repo.
