### ISSUE TITLE
Last Tutorial in Reports

### ISSUE THREAD

**Issue by Smithy31** [cwarwicker/moodle-block_elbp#28]
Hi 
The reports feature is working great thanks to your last update, I do have a quick question, when the Last tutorial option is added to a report it doesn't display any option menus under the options heading and when I run the report doesn't return any results.  

Regards

Smithy31

**Comment by cwarwicker** [comment]
I've pushed up a new patch (1.4.2) which should fix this now.

Also pushed up a fix for bc_dashboard block, as I noticed another error while I was checking this one.
