### ISSUE TITLE
elbp

### ISSUE THREAD

**Issue by Smithy31** [cwarwicker/moodle-block_elbp#39]
Hi
I am trying to install the elbp block, but when it goes to install I get the error below, I've downloaded the latest version from Github, not quite sure why the error is occurring any help would be greatly appreciated.

block_elbp
XML database file errors found

More information about this error

×Debug info: Errors found in XMLDB file: Problem loading table lbp_target_set_attributes, Problem loading index changeme, Empty FIELDS attribute
Error code: ddlxmlfileerror
×Stack trace:
line 352 of /lib/ddl/database_manager.php: ddl_exception thrown
line 368 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 902 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 446 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1754 of /lib/upgradelib.php: call to upgrade_plugins()
line 699 of /admin/index.php: call to upgrade_noncore()

**Comment by cwarwicker** [comment]
Hi,

What version of Moodle are you installing onto? (They only support up to 3.3 at the moment)

**Comment by Smithy31** [comment]
Hi
I'm running Moodle version 3.3.2

**Comment by cwarwicker** [comment]
Can you try again now, there was an errant index in the /db/install.xml file which I've removed now.

You can just download that one file and replace, instead of the whole thing again.

**Comment by Smithy31** [comment]
Hi 
It works perfect now :-)

Kind Regards
