### ISSUE TITLE
Missing tab in target plugin settings

### ISSUE THREAD

**Issue by Smithy31** [cwarwicker/moodle-block_elbp#40]
Hi I have set up my target section and I can add new targets, but when students logon they are unable to set their own targets, when I go into the configuration section of the targets plugin I only have 2 tab main and settings, on our old site we had 3 tabs main, targets and target sets.  I'm not quite sure what I've done or whether theses two issues are linked.

I have attached two screen shots, any help with this issue would be greatly appreciated.

Kind regards,

Paul
![old site target tabs](https://user-images.githubusercontent.com/40595356/46861966-c7fcdd80-ce0b-11e8-8dbe-bf7867fd5ed3.GIF)
![new site target tabs](https://user-images.githubusercontent.com/40595356/46861977-cdf2be80-ce0b-11e8-83bd-2fd30b08b068.GIF)

**Comment by cwarwicker** [comment]
Hi,

I removed Target Sets at the moment, as I was planning eventually to improve them and implement the same thing into Course Reports.

Have you checked that the Authenticated User role has the 'add_target' permission? That should allow students to add their own. Might also want 'update_target' to edit them.

**Comment by cwarwicker** [comment]
Can you run a permissions check on one of the students and see what the add_target capability actually comes out as? Maybe another role is overriding it.

**Comment by Smithy31** [comment]
Hi
You were spot on it was a permissions setting, it's all working great now thank you for your help.

Kind regards,

Paul
